In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)

In [3]:
a

array([0.61333129, 0.47720858, 0.79871751, 0.58142093, 0.56525249])

In [7]:
a.reshape(1, -1)

array([[0.61333129, 0.47720858, 0.79871751, 0.58142093, 0.56525249]])

In [6]:
np.shape(np.array([1,2,3,4,5,5]))

(6,)

In [1]:
from sklearn.datasets import make_regression

In [6]:
X,y =make_regression(n_samples=15,n_informative=5,n_features=10,n_targets=6)

In [8]:
X

array([[-2.14043403e+00, -6.25557036e-01, -9.87632451e-01,
        -6.87015835e-01,  1.32717999e+00,  4.75697595e-01,
        -1.68500226e-01, -5.94410665e-02,  7.68436418e-01,
         7.75165466e-02],
       [-7.23994827e-01,  1.09625368e+00, -6.59682827e-01,
        -1.84243498e+00, -1.30603537e+00, -9.14222986e-01,
        -1.75524783e+00,  2.68937364e-01, -1.09377138e+00,
        -1.10437100e+00],
       [ 1.68688683e-01, -1.86588418e-01, -1.40003586e+00,
        -1.51458643e+00, -8.50027448e-01, -6.14792814e-01,
        -1.98920336e-01, -6.04692069e-01, -1.43480455e+00,
        -4.72624088e-01],
       [-1.04334513e+00, -2.58819429e-01, -1.53745383e+00,
        -7.07142473e-01,  1.27940822e+00, -5.32269351e-01,
         1.96224634e+00, -1.54623664e+00,  2.17866171e-02,
         1.60933073e+00],
       [ 3.73472752e-01,  1.36094505e+00, -8.72227938e-01,
         6.17882924e-01,  5.24221311e-01,  7.90647880e-01,
        -1.55709505e+00, -7.87401963e-01, -1.22016178e+00,
        -1.