In [30]:
from collections import deque
from random import sample
import numpy as np
from math import cos, sin, pi

transitions = deque(maxlen=20)

In [3]:
transitions.append([1,2,3])

In [4]:
transitions.append([3,3,3])

In [5]:
sample(transitions, 10)

ValueError: Sample larger than population or is negative

In [314]:
array = np.zeros((6,6))

In [315]:
old_agent = [-4,1]
array[old_agent[0], old_agent[1]] = 1
old_coin = [-4,2]
array[old_coin[0], old_coin[1]] = 2

In [316]:
array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [317]:
"""
Lyle Scott, III  // lyle@ls3.io
Multiple ways to rotate a 2D point around the origin / a point.
Timer benchmark results @ https://gist.github.com/LyleScott/d17e9d314fbe6fc29767d8c5c029c362
"""
from __future__ import print_function

import math
import numpy as np


def rotate_origin_only(xy, radians):
    """Only rotate a point around the origin (0, 0)."""
    x, y = xy
    xx = x * math.cos(radians) + y * math.sin(radians)
    yy = -x * math.sin(radians) + y * math.cos(radians)

    return int(xx), int(yy)


def rotate(point, degree):
    theta = math.radians(degree)
    
    return rotate_origin_only(point, theta)

In [318]:
x, y = rotate(old_agent, 90)

In [319]:
x,y

(0, 4)

In [320]:
array[x,y], array[old_agent[0], old_agent[1]] = array[old_agent[0], old_agent[1]], array[x,y]

In [321]:
x, y = rotate(old_coin, 90)

In [322]:
array[x,y], array[old_coin[0], old_coin[1]] = array[old_coin[0],old_coin[1]], array[x,y]

In [323]:
array

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [297]:
b = [1, 1]

In [202]:
agent[0], agent[1] = old_agent[0]-b[0], old_agent[1]-b[1]

In [203]:
agent

[2, 0]

In [204]:
coin[0], coin[1] = old_coin[0]-b[0], old_coin[1]-b[1]

In [205]:
coin

[2, 1]

In [206]:
x = int(agent[0] * cos(pi/180 *-90) - agent[1] * sin(pi/180 *-90))

In [207]:
y = int(agent[0] * sin(pi/180 *-90) + agent[1] * cos(pi/180 *-90))

In [208]:
x,y

(0, -2)

In [209]:
q = int( coin[0] * cos(pi/180 *-90) - coin[1] * sin(pi/180 *-90) )

In [210]:
p = int( coin[0] * sin(pi/180 *-90) + coin[1] * cos(pi/180 *-90) )

In [211]:
q,p

(1, -2)

In [212]:
array[x,y], array[old_agent[0], old_agent[1]] = array[old_agent[0], old_agent[1]], array[x,y]

In [213]:
array[q,p], array[old_coin[0], old_coin[1]] = array[old_coin[0], old_coin[1]], array[q,p]

In [214]:
array

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])